---
language: python
python: "2.7"
services:
  - docker
before_install:
  # Pull container
  - 'sudo docker pull mkde/centos:7'
  # Customize container
  - 'sudo docker build --rm=true --file=tests/Dockerfile --tag=centos_cognos:latest tests'

script:
  # Prepare tests
  - container_id=$(mktemp)

    # Run container in detached state
  - 'sudo docker run --privileged=true --detach --volume="${PWD}":/etc/ansible/roles/cognos centos_cognos:latest "/sbin/init" > "${container_id}"'

  # Syntax under docker 
  - 'sudo docker exec --tty "$(cat ${container_id})" env ansible-playbook /etc/ansible/roles/cognos/examples/full_example.yml --syntax-check'

  # Check if it downloaded the binary
  - 'sudo docker exec --tty "$(cat ${container_id})" env ls /tmp/cognos.tar.gz'

  # Run playbook
  - 'travis_wait sudo docker exec --tty "$(cat ${container_id})" env ansible-playbook /etc/ansible/roles/cognos/examples/docker_test.yml --skip-tags dont-on-docker'

  # Test role idempotence.
  - >
    travis_wait sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/cognos/examples/docker_test.yml --skip-tags dont-on-docker
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'
