---
  - name: Installing Cognos pre requisites packages - RedHat
    yum: name="{{ item }}" state=installed update_cache={{make_cache}} disable_gpg_check=yes
    tags: ['packages', 'setup']
    with_items: "{{cognos_packages}}"
